database update
CollaborativeEconomics/monorepo pull request #5
Opened 2024-10-14 20:18 UTC by kuyawa

database update

2024-10-21 15:32 UTC, JulianKingman requested changes
This is a great PR! I appreciate all you've done to match the typing, structure, and format. There's a lot of care and attention here.

There are a few things to clean up (some generated files), and some places we can rely on type inference (return type of the database functions, the type exports from `@prisma/client`), and getting `biome` set up with your IDE will make the formatting consistent.

I resolved the `rabbit` reviews I disagree with, most of its suggestions are small and make sense.

2024-10-21 15:32 UTC, JulianKingman commented on packages/database/src/database/events.ts
> +export async function getEvents(query:EventQuery): Promise<Events|Array<Events>|null> {
same thing with these functions, remove the return type

2024-10-21 15:32 UTC, JulianKingman commented on packages/database/src/database/events.ts
> +  }
Good suggestion

2024-10-21 15:32 UTC, JulianKingman commented on packages/database/src/database/events.ts
> +  console.log('NEWEVENT', result)
meh, whatever. We'll add a universal solution later.

2024-10-21 15:32 UTC, JulianKingman commented on packages/database/src/database/impact.ts
> +}
Good idea

2024-10-21 15:32 UTC, JulianKingman commented on packages/database/src/prisma/generate.js
I don't think we need this file, types are automatically generated from Prisma schema now

2024-10-21 15:32 UTC, JulianKingman commented on packages/database/src/prisma/models.ts
Shouldn't be necessary. We can import types like TokenBoundAccount or Account everywhere from `@prisma/client`. Prisma does some black magic to make that possible.

2024-10-21 15:32 UTC, JulianKingman commented on packages/database/src/prisma/schema.prisma
> +  network String? @db.VarChar(10)
Will this make signing in any harder, or should it just work?

2024-10-21 15:32 UTC, JulianKingman commented on packages/database/src/prisma/schema.prisma.bak
Let's be fearless! You can delete this.

2024-10-21 15:32 UTC, JulianKingman commented on packages/ipfs/jest.config.d.ts
looks like these jest compiled files should be deleted

2024-10-22 16:01 UTC, kuyawa commented on packages/ipfs/jest.config.js
> +export default config;
File removed

2024-10-22 16:16 UTC, kuyawa commented on packages/database/src/database/tokenBoundAccounts.ts
> +}
It may have many, we just need the first in this case

2024-10-22 16:17 UTC, kuyawa commented on packages/database/src/database/tokenBoundAccounts.ts
> +}
Multi-line per instruction is more readable and debuggable than multi-instruction per line

2024-10-22 16:18 UTC, kuyawa commented on packages/database/src/database/tokenBoundAccounts.ts
> +}
To log the result we need to capture it first, so it stays

2024-10-23 13:00 UTC, kuyawa commented on packages/database/src/database/events.ts
> +}
Leave it as it is

2024-10-23 13:01 UTC, kuyawa commented on packages/database/src/database/events.ts
> +  }
For readability, multilines of one statement is better than multi-statements in one line. Leave as is.

2024-10-23 13:02 UTC, kuyawa commented
Done

2024-10-23 14:47 UTC, JulianKingman approved these changes
Thanks!

2024-10-24 01:13 UTC, kuyawa commented on packages/universe-api/src/users/route.ts
> +import { createNewUser } from "@cfce/utils"
ok

2024-10-24 01:17 UTC, kuyawa commented on packages/database/turbo.json
> +  ],
ok

2024-10-24 01:17 UTC, kuyawa commented on packages/database/turbo.json
> +    "BLOB_READ_WRITE_TOKEN"
ok

2024-10-24 01:30 UTC, merged